### ISSUE TITLE
require autoload.php & Parsing Results

### ISSUE THREAD

**Issue by a-keramat** [cedarstudios/cedarmaps-php-sdk#1]
hi, I'm using this package in a Laravel project

I encountered 2 errors I hope it helps you find and fix them

1) the first one occurred when I tried to instantiate the CedarMaps
 
![image](https://user-images.githubusercontent.com/30770127/57369349-8ca86e80-71a2-11e9-9231-e893b46ad8f3.png)

2) the second one seems to be just a mis-spelling

![image](https://user-images.githubusercontent.com/30770127/57369483-e741ca80-71a2-11e9-9e52-4ebee32936bb.png)

as it's clear I use xampp on windows

**Comment by nimolix** [comment]
Hi,

Thanks for using CedarMaps!

Please have a look at the below thread:
https://stackoverflow.com/questions/23675320/adding-a-non-laravel-package-to-my-laravel-project-with-composer

Regarding your second question, I've updated the package. Please run `composer update` to get ride of that nasty notice!
